# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'MYDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.4'
    pod 'SnapKit', '~> 3.2.0'
    pod 'FMDB'
  # Pods for MYDemo

  target 'MYDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
